name: Publish App to store

on:
  workflow_dispatch:
    inputs:
      release-track:
        type: choice
        description: Release environment
        options:
          - internal
          - alpha
          - production
        default: production
      whats-new:
        type: string
        description: What's new text for Play Store (supports escape chars)
        # Don't shame me, this is in case I really have nothing new to write :)
        default: Nova versão com melhorias funcionais.
  # Publishes on internal track - alpha and production tracks are published manually
  push:
    tags:
      - '**'

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: write

env:
  RELEASE_TRACK: ${{ github.event_name == 'push' && 'internal' || inputs.release-track }}

jobs:
  publish-to-google-play:
    name: Publish to Google Play
    needs: [version, release]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: 'actions/checkout@v4'

      - name: 📦 - Copy server artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: true

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/${{ vars.GCP_PROJECT_ID }}/locations/global/workloadIdentityPools/${{ vars.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

      - name: 🔧 - Print release notes
        run: |
          mkdir releaseNotes/
          echo -ne "${{ inputs.whats-new }}" > releaseNotes/whatsnew-pt-PT

      - name: 🚀 - Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          packageName: me.l3n.pessoapensadora.pessoa_pensadora
          releaseFiles: artifacts/PessoaPensadora.aab
          track: ${{ env.RELEASE_TRACK }}
          whatsNewDirectory: releaseNotes/
